# Generated by Django 5.1.2 on 2024-10-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_facility_description_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=200),
            preserve_default=False,
        ),
    ]
